### ISSUE TITLE
Make a review

### ISSUE THREAD

**Issue by vonglasow** [vonglasow/packer#1]
Hey @jubianchi could you review it please ;)

**Comment by jubianchi** [comment]
I ran quickly through the code and everything seems good. I only saw some minor things:
- [here](https://github.com/vonglasow/packer/blob/master/preseed.cfg#L11-L19) you are creating a `packer` user. It seems good in the first place but it creates some sort of coupling between your VM and packer. I would rather create a generic user, for example `admin` to totally hide the fact that the VM is built with packer.
- [here](https://github.com/vonglasow/packer/blob/master/debian.json) I don't see any post-processor to build a vagrant box. This is probably exactly what you want but in the future, if you plan on adding vagrant support, you will have to [create an extra user](https://github.com/jubianchi/vagrant-boxes/blob/master/debian/wheezy/chef/preseed.cfg#L7-L12) required by vagrant and [configure his key](https://github.com/jubianchi/vagrant-boxes/blob/master/scripts/vagrant.sh). In my examples, I create the `vagrant` user in the pressed which is far from being good when building real prod VM: the preseed is tightly coupled to vagrant.
- I don't see anything related to virtualbox guest additions in your template. Here is [an example script](https://github.com/jubianchi/vagrant-boxes/blob/master/scripts/vbox.sh) to install them in the VM.

**Comment by vonglasow** [comment]
First of all, @jubianchi thanks for your feedback
- Firstly, I will change the main user (probably also the repository name) `admin` seems good.
- Secondly, you are right the goal is to build a vagrant box. I will add it thanks for extra links.
- Yes it was not taking into consideration for the first step, thanks again for extra links. I will see it.

**Comment by jubianchi** [comment]
:+1:
